version: "3.9"
services:
  db:
    image: postgres:12-alpine
    container_name: exanubes-dev-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=exanubes
      - POSTGRES_USER=exanubes
      - POSTGRES_DB=exanubes
    volumes:
      - ./pg-data:/var/lib/postgresql/data
